builds:
- binary: oniongrok
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
brews:
- tap:
    owner: cmars
    name: homebrew-oniongrok
    branch: main
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"
