version: '3'

volumes:
  nextcloud:
  db:
  oniongrok:

services:
  oniongrok:
    image: ghcr.io/cmars/oniongrok:main
    restart: always
    command: --secrets /var/lib/oniongrok/secrets.json app:80~80@nextcloud
    volumes:
      - oniongrok:/var/lib/oniongrok

  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
